### ISSUE TITLE
Unable to set breakpoints

### ISSUE THREAD

**Issue by KillyMXI** [phoityne/phoityne-vscode#10]
When I'm trying to set a breakpoint:
```
H>>= 
  Now, ghci launched and configuration done.
  Press F5 to start debugging.
  Or modify source code. it will be loaded to ghci automatically.
 
H>>= 
:break .Main 22
<interactive>:1:2: error: parse error on input `Main'
```
Instead of breakpoint, there is a grayed circle shown, with following messages:
```
unexpected break set result. "getBreakId" (line 3, column 6): unexpected end of input expecting "Breakpoint "
<interactive>:1:2: error: parse error on input `Main' H>>=
```
In the log file, there are only messages related to deleting such incomplete breakpoints:
```
2017-02-13 01:21:33 [ThreadId 3] ERROR phoityne - [deleteBreakPointOnGHCi] invalid delete break point. BreakPointData {nameBreakPointData = ".Main", filePathBreakPointData = "c:\\...\\Main.hs", lineNoBreakPointData = 17, breakNoBreakPointData = Nothing, conditionBreakPointData = Nothing, hitConditionBreakPointData = Nothing, hitCountBreakPointData = 0}
```
Main.hs contains "module Main where" line.

Windows 10
VSCode 1.9.1
GHC 8.0.1, stack 1.3.2
Haskell GHCi debug viewer Phoityne - Marketplace phoityne-vscode-0.0.10

For me it looks like a regression after update - it worked before 2017-02-05.
(Module was also renamed about that day. I don't see how it may affect the things, but mentioned it here just in case.)

**Comment by phoityne** [comment]
I can not reproduce reported problem,  investigating.

From avobe log, probably, vscode sent this path to phoityne.

`filePathBreakPointData = "c:\\...\\Main.hs"`

then phoityne got module name ".Main" from the path.
"." is invalid.

**Comment by KillyMXI** [comment]
Path was shortened by me when posting here.

I've tried to change the file name and the module definition.
It turned out that it works when filename is in lower case.
* Main.hs - not working;
* main.hs - works fine.

Module definition doesn't seem to affect anything.

So the question is, why the letter case makes difference here and how it gets that dot in front of module name.

**Comment by phoityne** [comment]
reproduced by putting Main.hs in the top directory of stack project.

Thank you for the report.
Fixing it in the next release.

**Comment by tomesdesign** [comment]
Hi, exactly same problem here. Renaming to main.hs is not helping.

I am running GHCi, version 8.0.2, 
MAC OS Sierra (10.12.3)
stack 1.1.2

**Comment by phoityne** [comment]
Thank you for the report.

You are right. Filename must be match with module name.
so that, filename for Main module is Main.hs.

Fixing it in the next release.

**Comment by KillyMXI** [comment]
New release Marketplace phoityne-vscode-0.0.11
I see no changes neither with this issue nor with column breakpoints or anything else.
Have you actually published the right code?

**Comment by phoityne** [comment]
Have you updated phoityne exe from hackage?
Just make sure, the version is 0.0.13.0. 

```
% stack update
% stack install phoityne-vscode
% phoityne-vscode --version
phoityne-vscode-0.0.13.0
%
% code
```

**Comment by KillyMXI** [comment]
Oh. Thanks.
Now it works.

It's easy to miss this step. Not sure if will I remember to do it next time. Maybe it worth to add some kind of version check and notification in VScode.

**Comment by phoityne** [comment]
I agree with you.
Actually, hackageVersion variable has already be added in launch.json for that purpose, 
but phoityne does not use it yet.
that's next enhancement.

Regards.
