### ISSUE TITLE
Debugger not progressing past IO

### ISSUE THREAD

**Issue by Lispeoir** [phoityne/phoityne-vscode#11]
When I run a simple little program like:

```
module Main where

sqr :: Integer -> Integer
sqr x = x * x

main :: IO ()
main = do
       putStrLn $ show (sqr 5)
       getLine >>= putStrLn
       putStrLn $ show (sqr 10)
```
Then:
(a) The debugger will only display the result of the first putStrLn action if I have a breakpoint on the getLine.
(b) GHCi doesn't seem to return after taking input from the getLine.

Thanks for the extension!

**Comment by phoityne** [comment]
Thank you for the report.
This is a limitation of phoityne, you can not use stdin while debugging.

I'll add this limitation in the Readme.
Regards.
