### ISSUE TITLE
Debug not working at all

### ISSUE THREAD

**Issue by rakesh-k** [phoityne/phoityne-vscode#13]
I have installed both the cabal and stack version of the packages and made sure that the stack module is in the path and yet the extension is not working.  When I try to debug the environment with the name 'ghci debug view phoityne' shows up but then nothing happens when I select it. I am using module version 0.0.12.0. Visual studio code version is 1.10.1. Do let me know if I need to supply some more info. I tried looking for log etc. but could not find any.

Any advice is highly appreciated.

**Comment by phoityne** [comment]
Hi.

> When I try to debug the environment with the name 'ghci debug view phoityne' shows up 
>  but then nothing happens when I select it. 

let me make sure, did you press F5 to start debugging?

> I tried looking for log etc. but could not find any.

Log file will be created in .vscode folder in the stack project folder.
But, without starting  debugging, the log file is not created.

Regards.

**Comment by rakesh-k** [comment]
The environments show up after pressing F5 and I do choose the  'ghci debug viewer phoityne' environment. I can see in the command window that the phoityne-vscode is in the path.  Is there a command line interface to starting the debugger that I can try? I was hoping to see some error/warning when debugger does not run.

**Comment by phoityne** [comment]
> The environments show up after pressing F5 and
>  I do choose the 'ghci debug viewer phoityne' environment. 

After selecting phoityne environment, is launch.json file show up?
then, press F5 again to start debugging.

Additionally, you can set log file and log level in launch.json file.

> Is there a command line interface to starting the debugger that I can try? 

Yes, just for confirmation, call phoityne with version option.

```
> phoityne-vscode --version
0.0.10.0

>
```

> I was hoping to see some error/warning when debugger does not run.

When vscode can not start debug adapter, vscode shows error messages on the command pallet.
After debug started, any errors will be logged to phoityne log file which you set in launch.json.

Let me know, are you using Linux OS?

**Comment by rakesh-k** [comment]
The `launch.json` file is not created - this may be because the debugger does not get started. When I try to use the debug terminal by entering some input, I get an error saying - start the debug session first
```
C:\Users\rakeshk>phoityne-vscode --version
phoityne-vscode-0.0.12.0
```
I am not using LinuX but rather on Windows. Is it supposed to work on Linux only?

**Comment by phoityne** [comment]
> I am not using LinuX but rather on Windows. Is it supposed to work on Linux only?

No, it isn't. Windows supported.

I think, guess, you have not open folder from vscode.
Could you try below to start stack project.

1. open command prompt.
2. cd to somewhere folder
3. run 'stack setup'
4. run 'stack new some_prj'
5. open vscode and open folder 'some_prj' from vscode menu.
6. press F5 to start debugging.(could be build error)
7. press F7 to start full build.
8. press F8 to start build and test.

Regards.

**Comment by rakesh-k** [comment]
works! Thanks for pointing that out.
