### ISSUE TITLE
Use phoityne without adding it to path.

### ISSUE THREAD

**Issue by Kesanov** [phoityne/phoityne-vscode#14]
Could you make it possible to use phoityne without adding to path? For example by calling `stack exec` ?

**Comment by phoityne** [comment]
Could be yes.
I see, by calling stack exec, you can run phoityne without setting PATH environment.

but, currently, for running phoityne, stack is not required. (not must be required. )
so, and I don't think that stack is always supposed to be installed on user PC.
though, many people use stack.

**Comment by phoityne** [comment]
Please add new issue if there are more/other problems.
