### ISSUE TITLE
adding main args setting to launch.json

### ISSUE THREAD

**Issue by phoityne** [phoityne/phoityne-vscode#15]
set main args by ghci :set args command.

this enhancement has been commited.

**Comment by phoityne** [comment]
released with version-0.0.14.0.

**Comment by akshay2000** [comment]
I have put following in `launch.json` but I don't see any args with `getArgs` call.

    "mainArgs": "C:\\path\\to\\file.txt"

Version is 0.0.12 downloaded from the marketplace.

**Comment by phoityne** [comment]
Have you updated phoityne exe from hackage?
Just make sure, the version is 0.0.14.0.

```
% stack update
% stack install phoityne-vscode
% phoityne-vscode --version
phoityne-vscode-0.0.14.0
%
% code
```

**Comment by akshay2000** [comment]
Works like a charm. Thanks!
