### ISSUE TITLE
Exit on stdin eof

### ISSUE THREAD

**Issue by alanz** [phoityne/phoityne-vscode#16]
Consider updating the `ioLoop` to check for eof when reading, and then exit.

Otherwise the process hangs around if it is not shut down cleanly.

See https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/Control.hs#L58

**Comment by phoityne** [comment]
Thank you for the report.
I'll check it out.

**Comment by phoityne** [comment]
fixed in release-0.0.14.0.
