### ISSUE TITLE
main-is TARGET? and default is Spec.hs ?

### ISSUE THREAD

**Issue by varosi** [phoityne/phoityne-vscode#19]
Start debugging my application debugger gives me two problems:
```
stack ghci --test --no-load --no-build --main-is TARGET in d:\ProcessJIRA 
Configuring GHCi with the following packages: ProcessJIRA
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from C:\Users\home\AppData\Roaming\ghc\ghci.conf
Prelude> :set prompt "H>>= "
H>>= :set prompt2 "H>>= "
H>>= :load d:\ProcessJIRA/test/Spec.hs
<no location info>: error:
    can't find file: d:\ProcessJIRA/test/Spec.hs
Failed, modules loaded: none.
H>>= 
load file fail.[d:\ProcessJIRA/test/Spec.hs] file load error. 'd:\ProcessJIRA/test/Spec.hs'startup load error. d:\ProcessJIRA/test/Spec.hs
:break Main 12
<no location info>: error:
    Could not find module `Main'
    It is not a module in the current program, or in any known package.
H>>= 
```
1. Why it infers that main is TARGET, when it is "main" actually?
2. Why it tries to open Spec.hs when there is no such file or configuration?

**Comment by phoityne** [comment]
These are just default setting value.
You can configure them in .vscode/launch.json file to appropriate value of your project.
(startup and ghciCmd variable)

Regards.

**Comment by varosi** [comment]
Great! It worked. Thanks!

It would be great if debugger could read .cabal files, so it takes information about targets from there. Would you like to create feature request here about it?

**Comment by phoityne** [comment]
I think launch.json configuration is enough to work.
(though, i prefer to choosing target from ui, like visual studio c++ )

Mostly, you just set startup hs file in launch.json.
phoityne automatically load it.

**Comment by varosi** [comment]
Thanks!
