### ISSUE TITLE
Not working on Linux?

### ISSUE THREAD

**Issue by ghost** [phoityne/phoityne-vscode#2]
Hi, 

After running `stack install phoityne-vscode` and adding the executable to my PATH directory in Ubuntu 16.04, VSCode shows the following message: "phoityne-vscode.exe is not found. Run `stack install phoityne-vscode`, and put it to PATH environment." Does your extension work on Linux?, am I missing something?

Thanks!

**Comment by phoityne** [comment]
> Does your extension work on Linux?

Yes, it does.
On Ubuntu16.04 and CentOS7, it works. (I checked today.)

> am I missing something?

No, I think you missing nothing.
Just make sure again that phoityne-vscode is on your PATH environment.
In a terminal, you can confirm it like below.

`$ phoityne-vscode --version`
`phoityne-vscode-0.0.10.0`
` `
`$ code`
`   (vscode will be started)`

**Comment by ghost** [comment]
You were right, I did not add the folder to my PATH directory properly. Thank you very much for the response.
Also, your extension is great, congrats!
