### ISSUE TITLE
During stopping on breakpoints selection is one character less

### ISSUE THREAD

**Issue by varosi** [phoityne/phoityne-vscode#20]
![image](https://user-images.githubusercontent.com/6051718/27838055-cd130148-60f0-11e7-940c-653f27d68d61.png)

Seems like GHCi (8.0.2) is giving one character less. I don't know why.

**Comment by phoityne** [comment]
Thanks for the report.

This is a new feature of vscode-1.13.0.[#8851](https://github.com/Microsoft/vscode/issues/8851)
It seems that end column number(*) from ghci is correct.

I am wondering whether phoityne should add 1 to end column number.
(or this might be an issue of vscode ui.)

(*) char count number, mightbe.

**Comment by varosi** [comment]
I think that Phoityne/VSCode should mark it and not GHCi itself, because 38th column is at character 's' which is correct.

**Comment by phoityne** [comment]
fixed in phoityne-vscode-0.0.18.0.
