### ISSUE TITLE
debugger hangs

### ISSUE THREAD

**Issue by adlaika** [phoityne/phoityne-vscode#22]
When I click the "Start Debugging" button, the progress bar starts moving, and `stack ghci --test --no-load --no-build --main-is TARGET in /Users/marnold/Code/lambda/cloud-seeder` shows up in the "DEBUG CONSOLE" window, and then...nothing else happens. The "Continue" button remains grayed out. Eventually I hit the "Stop" button twice, causing the progress bar to stop and the debug control buttons to disappear.

As far as I can tell, I've followed the installation instructions to the letter. `phoityne-vscode` is present in my path.

**Comment by phoityne** [comment]
Hi.
Could you run build by pressing F7, and run test by pressing F8.

After starting F5, if nothing out in console, it might be because of taking a long time for project building. (especialy, the first time.)

**Comment by adlaika** [comment]
How long is a "long time"? I've let it run for an hour+ and it still just
says `stack ghci --test --no-load --no-build --main-is TARGET in
/Users/marnold/Code/lambda/cloud-seeder` 
in the DEBUG OUTPUT window...
pressing any and all of the F keys and letting their associated functions
run doesn't seem to affect this.

**Comment by adlaika** [comment]
here's the logfile contents: 
```
2017-07-19 08:24:37 [ThreadId 11] INFO phoityne - [REQUEST] LaunchRequest 
  { seqLaunchRequest = 2
  , typeLaunchRequest = "request"
  , commandLaunchRequest = "launch"
  , argumentsLaunchRequest = LaunchRequestArguments 
    { noDebugLaunchRequestArguments = Nothing
    , nameLaunchRequestArguments = "ghci debug viewer Phoityne"
    , typeLaunchRequestArguments = "ghc"
    , requestLaunchRequestArguments = "launch"
    , startupLaunchRequestArguments = "/Users/marnold/Code/lambda/cloud-seeder/test/Spec.hs"
    , workspaceLaunchRequestArguments = "/Users/marnold/Code/lambda/cloud-seeder"
    , logFileLaunchRequestArguments = "/Users/marnold/Code/lambda/cloud-seeder/.vscode/phoityne.log"
    , logLevelLaunchRequestArguments = "INFO"
    , ghciPromptLaunchRequestArguments = "H>>= "
    , ghciCmdLaunchRequestArguments = "stack ghci --test --no-load --no-build --main-is TARGET"
    , stopOnEntryLaunchRequestArguments = True
    , mainArgsLaunchRequestArguments = Just ""
  }}
  
2017-07-19 08:24:37 [ThreadId 11] INFO phoityne - [EVENT]
  { "seq":2
  , "type":"event"
  , "event":"output"
  , "body":
    { "category":"stdout"
    , "output":"stack ghci --test --no-load --no-build --main-is TARGET in /Users/marnold/Code/lambda/cloud-seeder \n"
    , "data":null
  }}
```

**Comment by phoityne** [comment]
Thanks for the log report.
Could you run below command on the terminal, and let me know the output results.
```
> cd /Users/marnold/Code/lambda/cloud-seeder
> stack ghci --test --no-load --no-build --main-is TARGET
```

Regards.

**Comment by adlaika** [comment]
```
stack ghci --test --no-load --no-build --main-is TARGET
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: cloud-seeder
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/marnold/.ghci
>
```

**Comment by phoityne** [comment]
Could you try adding "--ghci-options -ignore-dot-ghci" option to stack command in .vcode/lanch.json file.

`"ghciCmd": "stack ghci --test --no-load --no-build --main-is TARGET --ghci-options -ignore-dot-ghci",`

**Comment by phoityne** [comment]
Please add new issue if there are more/other problems.
