### ISSUE TITLE
Care to put an example configuration?

### ISSUE THREAD

**Issue by agocorona** [phoityne/phoityne-vscode#23]
Despite the videos, the documentation in VSCode seems to lack some basic things like example configurations. Running a VSCode extension is for me more difficult than understanding protofunctoidal arrowized contravariantoids in Haskell.

**Comment by phoityne** [comment]
Hi.
I'm thinking of preparing quick start document,
with startup project [(like these)](https://github.com/phoityne/stack-project-template), and introducing how to debug in VSCode.

I will put some configuration files(launch.json) there.
(and readme of vscode extension too.)

**Comment by phoityne** [comment]
added some config examples to README. (ver0.0.15)
