### ISSUE TITLE
Debugger doesn't run on heavier projects without implicit Prelude

### ISSUE THREAD

**Issue by varosi** [phoityne/phoityne-vscode#24]
Debugging command line is like:
```stack ghci project:project-gui --stack-yaml stack-windows.yaml --no-load --no-build --main-is main --ghci-options -fprint-evld-with-show```

When I press F5 and it tries to run this command line but hangs. If I start this from command-line on Windows - everything is fine. I think may be it hangs on output parsing. 

This is what command-line execution gives. Have in mind that there is a prompt and type information is working, no matter that you see an error. This error is not visible in VS Code, too.
```
The following GHC options are incompatible with GHCi and have not been passed to it: -Werror -threaded -O2
Configuring GHCi with the following packages: vraybench
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
ghc.EXE: addLibrarySearchPath: C:\Users\home\AppData\Local\Temp\stack372536\wxc-0.92.2.0 (Win32 error 3): The system cannot find the path specified.
Loaded GHCi configuration from C:\Users\home\AppData\Roaming\ghc\ghci.conf
>
```

**Comment by varosi** [comment]
hm, further investigation show that on smaller projects with default Prelude, it's working.
May be it expect to get a prompt "Prelude> ", but it gets only "> ". Because we use custom Prelude in our project.
This is set in cabal file, like that:
```default-extensions:  NoImplicitPrelude```

**Comment by varosi** [comment]
I suspect another problem. If people make a custom prompt into ghci.conf then this parsing will be confused again. 
One way to cope with that is to send ":set prompt ..." command without waiting for all text to come (and concrete prompt as well) and then wait to see new prompt output from GHCi.

**Comment by varosi** [comment]
A dirty workaround to this is to add: ```:set prompt "Prelude> "``` to C:\Users\{user}\AppData\Roaming\ghc\ghci.conf

**Comment by phoityne** [comment]
What you suspect and your guess above is completely correct.
And this is a limitation of phoityne.

But, I will add initial prompt variable in the launch.json file.
so that, user can change it for their run environment.

**Comment by phoityne** [comment]
added "ghciInitialPrompt" variable in the launch.json. (ver0.0.15)
