### ISSUE TITLE
Cannot put break point on a module situated in a file with different name

### ISSUE THREAD

**Issue by varosi** [phoityne/phoityne-vscode#25]
If you have file named GUIMain.hs containing module Main you cannot put a break point in it. 
It works only if file name and module name match.

":break" command needs a module name, not a file name. So all files should be enumerated for modules to make a mapping between file name and module name.

**Comment by phoityne** [comment]
Thank you for the report.
This is a limitation of phoityne.

I'll add this limitation to Readme.
phoityne  can handle modules which match its folder hierarchy and file name.
Regards.

**Comment by phoityne** [comment]
Added a functionality of getting module name which is defined in startup hs file.
Now, you are able to  put any name to startup hs file.
(ver0.0.15)

**Comment by varosi** [comment]
Currently I have project with:
Src/Main.hs
Lib/Math.hs

Math.hs has module Math.

When I try to add breakpoint in it or in any other file in Lib/ folder I get error, that there is no:
Lib.Math module. Is it possible Phoityne not to add folder names as prefixes, but to use module name that is defined into the file itself?

**Comment by phoityne** [comment]
> When I try to add breakpoint in it or in any other file in Lib/ folder I get error, that there is no:
 
There is a limitation that first character of top src folder name must be lowercase.
  - Src -> src
  - Lib -> lib

> Is it possible Phoityne not to add folder names as prefixes, but to use module name that is defined into the file itself?

Yes it is.  I'll look into it.
regards.
