### ISSUE TITLE
I have the follow exception [macOS High Sierra]

### ISSUE THREAD

**Issue by AbrahamAlcaina** [phoityne/phoityne-vscode#26]
Exception has occurred.
_exception = GHC.Exception.SomeException
               (/Users/abraham/.hspec: getFileStatus: does not exist (No such file or directory))

**Comment by phoityne** [comment]
Hi.

How is the console output like?
and let me know how to reproduce it.

**Comment by AbrahamAlcaina** [comment]
Sorry for the noise, It was my fault. 
I use `{-# OPTIONS_GHC -F -pgmF hspec-discover #-}` in my Spec but also I included a main

**Comment by adlaika** [comment]
@AbrahamAlcaina how did you solve this? I have the same issue: `test/Main.hs` consists of `{-# OPTIONS_GHC -F -pgmF hspec-discover #-}`. I have no `Spec.hs` file, though.
