### ISSUE TITLE
Debugger crashes on launch

### ISSUE THREAD

**Issue by hagen93** [phoityne/phoityne-vscode#27]
Just installed VS Code with this extension (along with Haskell Syntax Linter, haskell-linter and Haskell ghc-mod) under macOS High Sierra and I can't get it to work at all. When I select "Start debugging (F5)" and then ghci debug viewer Phoityne it just dies with the debug console showing the following message:

```
[CRITICAL]<launch> request parce error.
Content-Length: 144

{"command":"launch","arguments":{"type":"ghc","request":"launch","__sessionId":"16e869ec-1e82-4b09-a59e-ad41be2c022c"},"type":"request","seq":2}
"Error in $.arguments: When parsing the record LaunchRequestArguments of type Phoityne.VSCode.TH.LaunchRequestArgumentsJSON.LaunchRequestArguments the key name was not present."
`stack update` and install new phoityen-vscode.
Or check information on https://marketplace.visualstudio.com/items?itemName=phoityne.phoityne-vscode
[disconnectRequestHandler] ghci not started.
```

Tried the suggested "stack update" but no luck. Any ideas?

**Comment by phoityne** [comment]
It seems that somthing is wrong with .vscode/launch.json file.
Could you try below steps?

1. delete file ".vscode/launch.json"
2. select debug adapter on debug window top menu (list menu).
3. start debugging

step2 will recreate newest launch.json file.

**Comment by hagen93** [comment]
I figured it out. The launch.json file fails to autocreate if trying to debug a single file. The thing you want to debug has to be opened as a project instead.
