### ISSUE TITLE
Files with space in their path

### ISSUE THREAD

**Issue by Tirael90** [phoityne/phoityne-vscode#28]
Hello,
on Windows when you have a file with a space in the path (e.g. C:\Users\Here is space\main.hs)
then starting debugging (or saving the fail while debugging) will not initialize properly because in ghci> :load C:\Users\Here is space\main.hs will result in error. Adding just quotes does not solve the issue you also have to change the backslashes to slashes. So the command it should run is ghci> :load "C:/Users/Here is space/main.hs".
Can you please fix?
Keep up the good work!

**Comment by phoityne** [comment]
Thanks for the report.

I think you are saying about startup hs file.
Could you try setting startup variable in .vscode/launch.json like below ?

```
e.g.
  "startup": "\"C:\\Users\\phoityne\\here is space\\stack_project\\app\\Main.hs\""
```
That should be worked.

Anyway, I will add a function to add double quotes and escape backslash of startup hs file path string automatically.

**Comment by Tirael90** [comment]
That would probably work, unfortunately I can't do that as I'm using ${workspaceRoot} and ${file} and I can't modify them (at least I don't know how).

**Comment by phoityne** [comment]
Added a functionality of escaping statup file path.
(ver0.0.15)
