### ISSUE TITLE
Space in filename and reload on save

### ISSUE THREAD

**Issue by Tirael90** [phoityne/phoityne-vscode#29]
Hello,
I saw you fixed the issue with spaces in filenames in startup option which is awesome, thank you. Unfortunately this exact issue is still present on auto reload after saving. For example:
`Filepath: C:\Users\here is space\main.hs`
This is now correctly loaded on startup even when you use environment variables(like ${file}) in launch.json. But if I save the file and auto reload kicks in, I get an error:
`Couldn't read "\"C:\\Users\\here is space\\main.hs\"" as String`

Keep up the awesome work!

**Comment by phoityne** [comment]
Thank you for the report.

I will fix it in the next release.

**Comment by phoityne** [comment]
fixed in phoityne-vscode-0.0.18.0.
