### ISSUE TITLE
supporting Multi-root workspaces

### ISSUE THREAD

**Issue by phoityne** [phoityne/phoityne-vscode#30]
- have to version up tasks.json. 0.1.0 -> 2.0.0
- handle root path properly when putting breakpoints.

**Comment by phoityne** [comment]
Arg data of these breakpoint requests does not seem to be managed separately by each root folder.
- SetBreakpointsRequest
- SetFunctionBreakpointsRequest
- SetExceptionBreakpointsRequest

Prepared two root folders in a workspace, and ran phoityne debugger.
The two debugging processes are executed separately.
Then same breakpoint data was sent from ui to each root folder project.
The debug adapter can not distinguish which break setting should be used for which root folder.

REF: [#38134](https://github.com/Microsoft/vscode/issues/38134)

**Comment by minkir014** [comment]
That issue is now solved. You can provide that now.

**Comment by phoityne** [comment]
Thanks for your information.
I will try again the workspace feature of the vscode.
(forgot everything, can remember nothing...)

**Comment by minkir014** [comment]
Try to read the documentations again because lots of things has changed in the debug adapter protocol.

**Comment by phoityne** [comment]
Now, [VSCode Multi target debugging](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations) works fine with phoityne.

Adding [a sample launch.json](https://github.com/phoityne/hdx4vsc/issues/4) which using the compounds attribute to the document.
