### ISSUE TITLE
spawn EACCES

### ISSUE THREAD

**Issue by weak-head** [phoityne/phoityne-vscode#36]
vscode: 1.23.1
os: Linux Manjaro
phoityne-vscode extension: 0.0.19.0
phoityne-vscode: 0.0.22.0 / 0.0.23.0
other extensions: haskelly 0.5.4
resolver: lts-10.10

**Steps to reproduce**:

1. Download the latest phoityne template:

```
stack new package-name https://raw.githubusercontent.com/phoityne/stack-project-template/master/type-201711.hsfiles -p "module:Project.Top.Module" -p "module-path:Project/Top/Module" -p "paths-module:Paths_package_name"
```

2. Select haskell-debug-adapter

3. Set a breakpoint

4. hit F5

5. **spawn EACCES** pops up

6. nothing happens after it
  
launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "ghc",
            "name": "haskell-debug-adapter",
            "request": "launch",
            "internalConsoleOptions": "openOnSessionStart",
            "workspace": "${workspaceRoot}",
            "startup": "${workspaceRoot}/test/Spec.hs",
            "startupFunc": "",
            "startupArgs": "",
            "stopOnEntry": true,
            "mainArgs": "",
            "ghciPrompt": "H>>= ",
            "ghciInitialPrompt": "Prelude>",
            "ghciCmd": "stack ghci --test --no-load --no-build --main-is TARGET --ghci-options -fprint-evld-with-show",
            "ghciEnv": {},
            "logFile": "${workspaceRoot}/.vscode/phoityne.log",
            "logLevel": "WARNING"
        }
    ]
}
```

**Comment by phoityne** [comment]
Could you run below commands?

```
> cd your_project_directory
> stack test
```

If there is no error, could you try below commands.

```
> phoityne-vscode --version
> code
   press F5 to start debugging on the VSCode
```

**Comment by weak-head** [comment]
```
> stack test

Building all executables for `package-name' once. After a successful build of all of them, only specified executables will be rebuilt.
package-name-0.0.1.0: configure (lib + exe + test)
Configuring package-name-0.0.1.0...
package-name-0.0.1.0: build (lib + exe + test)
Preprocessing library for package-name-0.0.1.0..
Building library for package-name-0.0.1.0..

...

Registering library for package-name-0.0.1.0..
package-name-0.0.1.0: test (suite: package-name-test)
             
Progress: 1/2
Project.Top.Module.Control
  Control test
    with default
name=package-name, args=, loglevel=
      should throw exception

Finished in 0.0009 seconds
1 example, 0 failures
             
package-name-0.0.1.0: Test suite package-name-test passed
Completed 2 action(s).
```


```
> phoityne-vscode --version
phoityne-vscode-0.0.23.0
```

```
> code
F5
```

![error](https://user-images.githubusercontent.com/3947634/40793437-3a7117f6-64b1-11e8-813b-ada0cc702423.png)

This should be environment specific, because on my other PC with the exactly same setup and config everything works as a charm...

**Comment by phoityne** [comment]
Is there this shell file in your user home directory ?
and it should be executable. (called by vscode)

```
> ls -l ~/.vscode/extensions/phoityne*/phoityne-vscode.sh
-rwxrw-r--  . . . 
>
> ~/.vscode/extensions/phoityne*/phoityne-vscode.sh
   (can be run or spawn EACCESS ?)

  ctrl + c  to exit.

>
```

I am checking on centos.
Regards.

**Comment by weak-head** [comment]
Basically yes, here is the problem:

![shell](https://user-images.githubusercontent.com/3947634/40822100-727558e2-651f-11e8-9b0c-7f851e2a48b7.png)

Now the problem is solved.

But the question is how come on this environment I don't have the +x permission?
Shouldn't the attribute be adjusted during the plugin installation automatically?

Is it possible to use something like `source ./phoityne-vscode.sh` or `sh ./phoityne-vscode.sh` (as an option to call the script )? In such way the script could be executed even without the +x attribute.

**Comment by phoityne** [comment]
> But the question is how come on this environment I don't have the +x permission?
> Shouldn't the attribute be adjusted during the plugin installation automatically?

It supposed to be executable file, by plugin installation.

> Is it possible to use something like source ./phoityne-vscode.sh or sh ./phoityne-vscode.sh (as an option to call the script )? In such way the script could be executed even without the +x attribute.

Yes it is.
I will set runtime setting  to "sh" in the next release.
thanks.
