### ISSUE TITLE
stack install phoityne-vscode haskell-dap never completes.

### ISSUE THREAD

**Issue by Haskeller1** [phoityne/phoityne-vscode#39]
After waiting around 1 hour after executing the stack install phoityne-vscode haskell-dap command the installation did not complete. I killed GHC.exe and the following was printed to the terminal.

C:\Users\haava>stack install phoityne-vscode haskell-dap
phoityne-vscode-0.0.28.0: configure
phoityne-vscode-0.0.28.0: build

--  While building package phoityne-vscode-0.0.28.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.3.exe --builddir=.stack-work\dist\e626a42b build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\sr\global-project\.stack-work\logs\phoityne-vscode-0.0.28.0.log

    Configuring phoityne-vscode-0.0.28.0...
    Preprocessing executable 'phoityne-vscode' for phoityne-vscode-0.0.28.0..
    Building executable 'phoityne-vscode' for phoityne-vscode-0.0.28.0..
    [  1 of 107] Compiling Paths_phoityne_vscode ( .stack-work\dist\e626a42b\build\phoityne-vscode\autogen\Paths_phoityne_vscode.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Paths_phoityne_vscode.o )
    [  2 of 107] Compiling Phoityne.GHCi.Process ( app\Phoityne\GHCi\Process.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\GHCi\Process.o )
    [  3 of 107] Compiling Phoityne.GHCi.Command ( app\Phoityne\GHCi\Command.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\GHCi\Command.o )
    [  4 of 107] Compiling Phoityne.GHCi    ( app\Phoityne\GHCi.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\GHCi.o )
    [  5 of 107] Compiling Phoityne.VSCode.Constant ( app\Phoityne\VSCode\Constant.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\VSCode\Constant.o )
    [  6 of 107] Compiling Phoityne.VSCode.Type ( app\Phoityne\VSCode\Type.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\VSCode\Type.o )
    [  7 of 107] Compiling Phoityne.VSCode.Argument ( app\Phoityne\VSCode\Argument.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\VSCode\Argument.o )
    [  8 of 107] Compiling Phoityne.VSCode.Utility ( app\Phoityne\VSCode\Utility.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\VSCode\Utility.o )
    [  9 of 107] Compiling Phoityne.VSCode.TH.VariablesArgumentsJSON ( app\Phoityne\VSCode\TH\VariablesArgumentsJSON.hs, .stack-work\dist\e626a42b\build\phoityne-vscode\phoityne-vscode-tmp\Phoityne\VSCode\TH\VariablesArgumentsJSON.o )

OS: Windows 10 64 bit Version 1809 (OS Build 17763-292)
GHC: The Glorious Glasgow Haskell Compilation System, version 8.6.3

**Comment by phoityne** [comment]
There is an issue on ghc-8.6.3.
with this version, build will hang.
(because of using template haskell)
https://ghc.haskell.org/trac/ghc/ticket/16057

duplicate:https://github.com/phoityne/hdx4vsc/issues/2

Thank you for using phoityne.

**Comment by Haskeller1** [comment]
Thank you, was able to install it using:
stack install --resolver lts-12.26 phoityne-vscode haskell-dap
