### ISSUE TITLE
i got this error cant load souce

### ISSUE THREAD

**Issue by loyalpartner** [phoityne/phoityne-vscode#44]
![image](https://user-images.githubusercontent.com/1442249/57869365-78661080-7837-11e9-81d9-bd208446eede.png)

2019-05-16 23:50:04 [ThreadId 3] ERROR phoityne - setBreakpointRequest failed. [DAP][ERROR] loaded module can not find from path. <c:\Users\li\tmp\prettyJSON\Prettify.hs> [("Main","c:/Users/li/tmp/prettyJSON/Main.hs"),("Prettify",".\\Prettify.hs"),("PrettyJSON",".\\PrettyJSON.hs"),("SimpleJSON",".\\SimpleJSON.hs")] : Left "[DAP][ERROR] loaded module can not find from path. <c:\\Users\\li\\tmp\\prettyJSON\\Prettify.hs> [(\"Main\",\"c:/Users/li/tmp/prettyJSON/Main.hs\"),(\"Prettify\",\".\\\\Prettify.hs\"),(\"PrettyJSON\",\".\\\\PrettyJSON.hs\"),(\"SimpleJSON\",\".\\\\SimpleJSON.hs\")]"

**Comment by phoityne** [comment]
Hi.

Could you set logLevel "DEBUG" in the launch.json
and get the error log ?

Regards.

**Comment by loyalpartner** [comment]
CWD: C:\Users\li\tmp\prettyJSON 

CMD: stack ghci --test --no-load --no-build --main-is TARGET --ghci-options -fprint-evld-with-show --with-ghc=haskell-dap 



Note: No local targets specified, so a plain ghci will be started with no package hiding or package
      options.
      
      If you want to use package hiding and options, then you can try one of the following:
      
      * If you want to start a different project configuration
        than C:\sr\global-project\stack.yaml, then you can use stack init to create a new stack.yaml
        for the packages in the current directory. 
        
      * If you want to use the project configuration
        at C:\sr\global-project\stack.yaml, then you can add to its 'packages' field.
      
Configuring GHCi with the following packages: 
[DAP][INFO] start haskell-dap-0.0.13.0.
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Prelude>:set prompt "H>>= "

 H>>= :set prompt-cont "H>>= "

H>>= :load c:/Users/li/tmp/prettyJSON/Main.hs

[1 of 4] Compiling Prettify         ( Prettify.hs, interpreted )

[2 of 4] Compiling SimpleJSON       ( SimpleJSON.hs, interpreted )

[3 of 4] Compiling PrettyJSON       ( PrettyJSON.hs, interpreted )

[4 of 4] Compiling Main             ( C:\Users\li\tmp\prettyJSON\Main.hs, interpreted )

Ok, four modules loaded.

H>>= :module + *Prettify *SimpleJSON *PrettyJSON *Main

H>>= :dap-set-breakpoints SetBreakpointsRequest {seqSetBreakpointsRequest = 3, typeSetBreakpointsRequest = "request", commandSetBreakpointsRequest = "setBreakpoints", argumentsSetBreakpointsRequest = SetBreakpointsArguments {sourceSetBreakpointsArguments = Source {nameSource = Just "Main.hs", pathSource = "c:\\Users\\li\\tmp\\prettyJSON\\Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, breakpointsSetBreakpointsArguments = [SourceBreakpoint {lineSourceBreakpoint = 12, columnSourceBreakpoint = Nothing, conditionSourceBreakpoint = Nothing, hitConditionSourceBreakpoint = Nothing, logMessageSourceBreakpoint = Nothing}]}}

[DAP][INFO][dapSetBreakpointsCommand] c:/Users/li/tmp/prettyJSON/Main.hs -> Main

[DAP][INFO][dapSetBreakpointsCommand] delete src bps []

Breakpoint 0 activated at C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50

<<DAP>>Right (SetBreakpointsResponseBody {breakpointsSetBreakpointsResponseBody = [Breakpoint {idBreakpoint = Just 0, verifiedBreakpoint = True, messageBreakpoint = "", sourceBreakpoint = Source {nameSource = Just "Main", pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineBreakpoint = 12, columnBreakpoint = 8, endLineBreakpoint = 12, endColumnBreakpoint = 51}]})

<<DAP_CMD_END>>

H>>= :dap-set-breakpoints SetBreakpointsRequest {seqSetBreakpointsRequest = 4, typeSetBreakpointsRequest = "request", commandSetBreakpointsRequest = "setBreakpoints", argumentsSetBreakpointsRequest = SetBreakpointsArguments {sourceSetBreakpointsArguments = Source {nameSource = Just "Prettify.hs", pathSource = "c:\\Users\\li\\tmp\\prettyJSON\\Prettify.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, breakpointsSetBreakpointsArguments = [SourceBreakpoint {lineSourceBreakpoint = 34, columnSourceBreakpoint = Nothing, conditionSourceBreakpoint = Nothing, hitConditionSourceBreakpoint = Nothing, logMessageSourceBreakpoint = Nothing},SourceBreakpoint {lineSourceBreakpoint = 47, columnSourceBreakpoint = Nothing, conditionSourceBreakpoint = Nothing, hitConditionSourceBreakpoint = Nothing, logMessageSourceBreakpoint = Nothing}]}}

<<DAP>>Left "[DAP][ERROR] loaded module can not find from path. <c:\\Users\\li\\tmp\\prettyJSON\\Prettify.hs> [(\"Main\",\"c:/Users/li/tmp/prettyJSON/Main.hs\"),(\"Prettify\",\".\\\\Prettify.hs\"),(\"PrettyJSON\",\".\\\\PrettyJSON.hs\"),(\"SimpleJSON\",\".\\\\SimpleJSON.hs\")]"

<<DAP_CMD_END>>

H>>= 

  Now, ghci launched and configuration done.
  Press F5 to start debugging.
  Or modify source code. it will be loaded to ghci automatically.
 
H>>= :dap-continue ConfigurationDoneRequest {seqConfigurationDoneRequest = 5, typeConfigurationDoneRequest = "request", commandConfigurationDoneRequest = "configurationDone"}

Stopped in Main.main, C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50

_result :: IO () = _

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "breakpoint", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50] H>>= :dap-stacktrace StackTraceRequest {seqStackTraceRequest = 8, typeStackTraceRequest = "request", commandStackTraceRequest = "stackTrace", argumentsStackTraceRequest = StackTraceArguments {threadIdStackTraceArguments = 0, startFrameStackTraceArguments = Just 0, levelsStackTraceArguments = 20}}

<<DAP>>Right (StackTraceBody {stackFramesStackTraceBody = [StackFrame {idStackFrame = 0, nameStackFrame = "Main.main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 8, endLineStackFrame = 12, endColumnStackFrame = 51}], totalFramesStackTraceBody = 1})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50] H>>= :dap-scopes ScopesRequest {seqScopesRequest = 9, typeScopesRequest = "request", commandScopesRequest = "scopes", argumentsScopesRequest = ScopesArguments {frameIdScopesArguments = 0}}

<<DAP>>Right (ScopesBody {scopesScopesBody = [Scope {nameScope = "GHCi Local", variablesReferenceScope = 1, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False},Scope {nameScope = "GHCi Global", variablesReferenceScope = 2, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50] H>>= :dap-variables VariablesRequest {seqVariablesRequest = 10, typeVariablesRequest = "request", commandVariablesRequest = "variables", argumentsVariablesRequest = VariablesArguments {variablesReferenceVariablesArguments = 1}}

*** Ignoring breakpoint

<<DAP>>Right (VariablesBody {variablesVariablesBody = [Variable {nameVariable = "_result", valueVariable = "_", typeVariable = "IO ()", presentationHintVariable = Nothing, evaluateNameVariable = Nothing, variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:8-50] H>>= :dap-step-in StepInRequest {seqStepInRequest = 11, typeStepInRequest = "request", commandStepInRequest = "stepIn", argumentsStepInRequest = StepInArguments {threadIdStepInArguments = 0}}

Stopped in Main.main, C:\Users\li\tmp\prettyJSON\Main.hs:12:19-50

_result :: String = _

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "step", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-50] H>>= :dap-stacktrace StackTraceRequest {seqStackTraceRequest = 13, typeStackTraceRequest = "request", commandStackTraceRequest = "stackTrace", argumentsStackTraceRequest = StackTraceArguments {threadIdStackTraceArguments = 0, startFrameStackTraceArguments = Just 0, levelsStackTraceArguments = 20}}

<<DAP>>Right (StackTraceBody {stackFramesStackTraceBody = [StackFrame {idStackFrame = 0, nameStackFrame = "Main.main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 51},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 8, endLineStackFrame = 12, endColumnStackFrame = 51}], totalFramesStackTraceBody = 2})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-50] H>>= :dap-scopes ScopesRequest {seqScopesRequest = 14, typeScopesRequest = "request", commandScopesRequest = "scopes", argumentsScopesRequest = ScopesArguments {frameIdScopesArguments = 0}}

<<DAP>>Right (ScopesBody {scopesScopesBody = [Scope {nameScope = "GHCi Local", variablesReferenceScope = 1, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False},Scope {nameScope = "GHCi Global", variablesReferenceScope = 2, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-50] H>>= :dap-variables VariablesRequest {seqVariablesRequest = 15, typeVariablesRequest = "request", commandVariablesRequest = "variables", argumentsVariablesRequest = VariablesArguments {variablesReferenceVariablesArguments = 1}}

<<DAP>>Right (VariablesBody {variablesVariablesBody = [Variable {nameVariable = "_result", valueVariable = "'[' : '{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\26126' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : 'e' :\n'\"' : ':' : ' ' : '1' : '2' : '.' : '0' : '\\n' : '}' : ',' : '\\n' :\n'{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\20975' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : _ : _", typeVariable = "String", presentationHintVariable = Nothing, evaluateNameVariable = Just "_result", variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-50] H>>= :dap-step-in StepInRequest {seqStepInRequest = 16, typeStepInRequest = "request", commandStepInRequest = "stepIn", argumentsStepInRequest = StepInArguments {threadIdStepInArguments = 0}}

Stopped in Main.main, C:\Users\li\tmp\prettyJSON\Main.hs:12:19-26

_result :: Doc -> String = _

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "step", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-26] H>>= :dap-stacktrace StackTraceRequest {seqStackTraceRequest = 18, typeStackTraceRequest = "request", commandStackTraceRequest = "stackTrace", argumentsStackTraceRequest = StackTraceArguments {threadIdStackTraceArguments = 0, startFrameStackTraceArguments = Just 0, levelsStackTraceArguments = 20}}

<<DAP>>Right (StackTraceBody {stackFramesStackTraceBody = [StackFrame {idStackFrame = 0, nameStackFrame = "Main.main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 27},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 51},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 8, endLineStackFrame = 12, endColumnStackFrame = 51}], totalFramesStackTraceBody = 3})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-26] H>>= :dap-scopes ScopesRequest {seqScopesRequest = 19, typeScopesRequest = "request", commandScopesRequest = "scopes", argumentsScopesRequest = ScopesArguments {frameIdScopesArguments = 0}}

<<DAP>>Right (ScopesBody {scopesScopesBody = [Scope {nameScope = "GHCi Local", variablesReferenceScope = 1, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False},Scope {nameScope = "GHCi Global", variablesReferenceScope = 2, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-26] H>>= :dap-variables VariablesRequest {seqVariablesRequest = 20, typeVariablesRequest = "request", commandVariablesRequest = "variables", argumentsVariablesRequest = VariablesArguments {variablesReferenceVariablesArguments = 1}}

<<DAP>>Right (VariablesBody {variablesVariablesBody = [Variable {nameVariable = "_result", valueVariable = "_", typeVariable = "Doc -> String", presentationHintVariable = Nothing, evaluateNameVariable = Nothing, variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing}]})

<<DAP_CMD_END>>

[C:\Users\li\tmp\prettyJSON\Main.hs:12:19-26] H>>= :dap-step-in StepInRequest {seqStepInRequest = 21, typeStepInRequest = "request", commandStepInRequest = "stepIn", argumentsStepInRequest = StepInArguments {threadIdStepInArguments = 0}}

Stopped in Prettify.pretty, Prettify.hs:47:18-27

_result :: [Char] = _

best :: Int -> [Doc] -> [Char] = _

x :: Doc = _

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "step", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

[Prettify.hs:47:18-27] H>>= :dap-stacktrace StackTraceRequest {seqStackTraceRequest = 23, typeStackTraceRequest = "request", commandStackTraceRequest = "stackTrace", argumentsStackTraceRequest = StackTraceArguments {threadIdStackTraceArguments = 0, startFrameStackTraceArguments = Just 0, levelsStackTraceArguments = 20}}

<<DAP>>Right (StackTraceBody {stackFramesStackTraceBody = [StackFrame {idStackFrame = 0, nameStackFrame = "Prettify.pretty", sourceStackFrame = Source {nameSource = Nothing, pathSource = ".\\Prettify.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 47, columnStackFrame = 18, endLineStackFrame = 47, endColumnStackFrame = 28},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 27},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 51},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 8, endLineStackFrame = 12, endColumnStackFrame = 51}], totalFramesStackTraceBody = 4})

<<DAP_CMD_END>>

[Prettify.hs:47:18-27] H>>= 
[WARN] source command is not supported. ignored.
:dap-scopes ScopesRequest {seqScopesRequest = 25, typeScopesRequest = "request", commandScopesRequest = "scopes", argumentsScopesRequest = ScopesArguments {frameIdScopesArguments = 0}}

<<DAP>>Right (ScopesBody {scopesScopesBody = [Scope {nameScope = "GHCi Local", variablesReferenceScope = 1, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False},Scope {nameScope = "GHCi Global", variablesReferenceScope = 2, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False}]})

<<DAP_CMD_END>>

[Prettify.hs:47:18-27] H>>= :dap-variables VariablesRequest {seqVariablesRequest = 26, typeVariablesRequest = "request", commandVariablesRequest = "variables", argumentsVariablesRequest = VariablesArguments {variablesReferenceVariablesArguments = 1}}

<<DAP>>Right (VariablesBody {variablesVariablesBody = [Variable {nameVariable = "_result", valueVariable = "'[' : '{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\26126' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : 'e' :\n'\"' : ':' : ' ' : '1' : '2' : '.' : '0' : '\\n' : '}' : ',' : '\\n' :\n'{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\20975' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : _ : _", typeVariable = "[Char]", presentationHintVariable = Nothing, evaluateNameVariable = Just "_result", variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "best", valueVariable = "_", typeVariable = "Int -> [Doc] -> [Char]", presentationHintVariable = Nothing, evaluateNameVariable = Nothing, variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "x", valueVariable = "Concat (Concat (Char '[') (Concat (Concat (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '\"')) (Text \": \")) (Concat (Concat (Char '\"') (Concat (Char '\\23567') (Char '\\26126'))) (Char '\"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '\"')) (Text \": \")) (Text \"12.0\")) (Union (Char ' ') Line)))) (Char '}')) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '\"')) (Text \": \")) (Concat (Concat (Char '\"') (Concat (Char '\\23567') (Char '\\20975'))) (Char '\"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '\"')) (Text \": \")) (Text \"12.0\")) (Union (Char ' ') Line)))) (Char '}')) (Union (Char ' ') Line)))) (Char ']')", typeVariable = "Doc", presentationHintVariable = Nothing, evaluateNameVariable = Just "x", variablesReferenceVariable = 10, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing}]})

<<DAP_CMD_END>>

[Prettify.hs:47:18-27] H>>= :dap-step-in StepInRequest {seqStepInRequest = 27, typeStepInRequest = "request", commandStepInRequest = "stepIn", argumentsStepInRequest = StepInArguments {threadIdStepInArguments = 0}}

Stopped in Prettify.pretty.best, Prettify.hs:(50,7)-(57,50)

_result :: [Char] = _

col :: Int = 0

d ::

  Doc = Concat (Concat (Char '[') (Concat (Concat (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '"')) (Text ": ")) (Concat (Concat (Char '"') (Concat (Char '\23567') (Char '\26126'))) (Char '"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '"')) (Text ": ")) (Text "12.0")) (Union (Char ' ') Line)))) (Char '}')) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '"')) (Text ": ")) (Concat (Concat (Char '"') (Concat (Char '\23567') (Char '\20975'))) (Char '"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '"')) (Text ": ")) (Text "12.0")) (Union (Char ' ') Line)))) (Char '}')) (Union (Char ' ') Line)))) (Char ']')

ds :: [Doc] = []

nicest :: Int -> String -> String -> String = _

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "step", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

[Prettify.hs:(50,7)-(57,50)] H>>= :dap-stacktrace StackTraceRequest {seqStackTraceRequest = 29, typeStackTraceRequest = "request", commandStackTraceRequest = "stackTrace", argumentsStackTraceRequest = StackTraceArguments {threadIdStackTraceArguments = 0, startFrameStackTraceArguments = Just 0, levelsStackTraceArguments = 20}}

<<DAP>>Right (StackTraceBody {stackFramesStackTraceBody = [StackFrame {idStackFrame = 0, nameStackFrame = "Prettify.pretty.best", sourceStackFrame = Source {nameSource = Nothing, pathSource = ".\\Prettify.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 50, columnStackFrame = 7, endLineStackFrame = 57, endColumnStackFrame = 51},StackFrame {idStackFrame = 0, nameStackFrame = "pretty", sourceStackFrame = Source {nameSource = Nothing, pathSource = ".\\Prettify.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 47, columnStackFrame = 18, endLineStackFrame = 47, endColumnStackFrame = 28},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 27},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 19, endLineStackFrame = 12, endColumnStackFrame = 51},StackFrame {idStackFrame = 0, nameStackFrame = "main", sourceStackFrame = Source {nameSource = Nothing, pathSource = "c:/Users/li/tmp/prettyJSON/Main.hs", sourceReferenceSource = Nothing, origineSource = Nothing}, lineStackFrame = 12, columnStackFrame = 8, endLineStackFrame = 12, endColumnStackFrame = 51}], totalFramesStackTraceBody = 5})

<<DAP_CMD_END>>

[Prettify.hs:(50,7)-(57,50)] H>>= :dap-scopes ScopesRequest {seqScopesRequest = 30, typeScopesRequest = "request", commandScopesRequest = "scopes", argumentsScopesRequest = ScopesArguments {frameIdScopesArguments = 0}}

<<DAP>>Right (ScopesBody {scopesScopesBody = [Scope {nameScope = "GHCi Local", variablesReferenceScope = 1, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False},Scope {nameScope = "GHCi Global", variablesReferenceScope = 2, namedVariablesScope = Nothing, indexedVariablesScope = Nothing, expensiveScope = False}]})

<<DAP_CMD_END>>

[Prettify.hs:(50,7)-(57,50)] H>>= :dap-variables VariablesRequest {seqVariablesRequest = 31, typeVariablesRequest = "request", commandVariablesRequest = "variables", argumentsVariablesRequest = VariablesArguments {variablesReferenceVariablesArguments = 1}}

<<DAP>>Right (VariablesBody {variablesVariablesBody = [Variable {nameVariable = "_result", valueVariable = "'[' : '{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\26126' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : 'e' :\n'\"' : ':' : ' ' : '1' : '2' : '.' : '0' : '\\n' : '}' : ',' : '\\n' :\n'{' : '\"' : 'n' : 'a' : 'm' : 'e' : '\"' : ':' : ' ' : '\"' :\n'\\23567' : '\\20975' : '\"' : ',' : '\\n' : '\"' : 'a' : 'g' : _ : _", typeVariable = "[Char]", presentationHintVariable = Nothing, evaluateNameVariable = Just "_result", variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "col", valueVariable = "0", typeVariable = "Int", presentationHintVariable = Nothing, evaluateNameVariable = Just "col", variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "d", valueVariable = "Concat (Concat (Char '[') (Concat (Concat (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '\"')) (Text \": \")) (Concat (Concat (Char '\"') (Concat (Char '\\23567') (Char '\\26126'))) (Char '\"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '\"')) (Text \": \")) (Text \"12.0\")) (Union (Char ' ') Line)))) (Char '}')) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Char '{') (Concat (Concat (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'n') (Concat (Char 'a') (Concat (Char 'm') (Char 'e'))))) (Char '\"')) (Text \": \")) (Concat (Concat (Char '\"') (Concat (Char '\\23567') (Char '\\20975'))) (Char '\"'))) (Char ',')) (Union (Char ' ') Line)) (Concat (Concat (Concat (Concat (Concat (Char '\"') (Concat (Char 'a') (Concat (Char 'g') (Char 'e')))) (Char '\"')) (Text \": \")) (Text \"12.0\")) (Union (Char ' ') Line)))) (Char '}')) (Union (Char ' ') Line)))) (Char ']')", typeVariable = "Doc", presentationHintVariable = Nothing, evaluateNameVariable = Just "d", variablesReferenceVariable = 10, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "ds", valueVariable = "[]", typeVariable = "[Doc]", presentationHintVariable = Nothing, evaluateNameVariable = Just "ds", variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing},Variable {nameVariable = "nicest", valueVariable = "_", typeVariable = "Int -> String -> String -> String", presentationHintVariable = Nothing, evaluateNameVariable = Nothing, variablesReferenceVariable = 0, namedVariablesVariable = Nothing, indexedVariablesVariable = Nothing}]})

<<DAP_CMD_END>>

[Prettify.hs:(50,7)-(57,50)] H>>= :dap-continue ContinueRequest {seqContinueRequest = 32, typeContinueRequest = "request", commandContinueRequest = "continue", argumentsContinueRequest = ContinueArguments {threadIdContinueArguments = 0, exprContinueArguments = Nothing}}

[{"name": "ﾐ｡ﾃ�",

"age": 12.0

},

{"name": "ﾐ｡ｿｭ",

"age": 12.0

} ]

<<DAP>>Right (StoppedEventBody {reasonStoppedEventBody = "complete", descriptionStoppedEventBody = "", threadIdStoppedEventBody = 0, textStoppedEventBody = "", allThreadsStoppedStoppedEventBody = True})

<<DAP_CMD_END>>

H>>= :quit

Leaving GHCi.

ExitSuccess

**Comment by phoityne** [comment]
I reproduced it in my local project.
Could you run "stack init" in you project dir to create local stack.yaml ?
```
(stack message)
Note: No local targets specified, so a plain ghci will be started with no package hiding or package
options.

  * If you want to start a different project configuration
    than C:\sr\global-project\stack.yaml, then you can use stack init to create a new stack.yaml
    for the packages in the current directory. 
 ```

With local stack.yaml, it works, in my local project.

**Comment by loyalpartner** [comment]
tks!
