### ISSUE TITLE
launch.json not automatically generated

### ISSUE THREAD

**Issue by mentoc3000** [phoityne/phoityne-vscode#47]
After first creating a stack project, `launch.json`, `phoityne.log`, and `tasks.json` are not automatically generated after hitting f5 to start debugging. These files must be generated by going into the debugger menu and clicking the 'create a launch.json file' and selecting haskell-debug-adapter. 

Windows 10
VSCode 1.42.1
Stack 2.1.3
ghc 8.6.5

Steps to reproduce:
1. `stack new my-project`
1. open my-project in vscode
1. Change resolver to `lts-14.20` in `stack.yaml`
1. `stack setup`
1. Open `app/Main.hs`
1. Hit f5

Observations:
Nothing happens. Files are not created in `.vscode` directory.

**Comment by phoityne** [comment]
> These files must be generated by going into the debugger menu and clicking the 'create a launch.json file' and selecting haskell-debug-adapter.

Yes, this is right.
launch.json is created when you select the debug adapter.

This is newer setup movie.
![08_quickstart.gif](https://raw.githubusercontent.com/phoityne/hdx4vsc/master/docs/08_quickstart.gif)

Regards.
