### ISSUE TITLE
adding ghci run enviroment variable setting.

### ISSUE THREAD

**Issue by phoityne** [phoityne/phoityne-vscode#5]
There already has been add ghciEnv setting on launch.json.
But it is not uesed in phoityne-vscode yet.

**Comment by akshay2000** [comment]
Will this setting allow me to obtains args using `getArgs` from `System.Environment` package? If so, then this is awesome. Do we have an ETA on implementation?

**Comment by phoityne** [comment]
No, this won't.
This setting allow you to use getEnv.
I will check ":set args" ghci command for using getArgs.

**Comment by akshay2000** [comment]
That's great. This will be extremely helpful for my workflow. Is there any way we can contribute to this extension?

**Comment by phoityne** [comment]
Thanks for your contribution.
for accepting pull request, I'll commit extension code to github here, ASAP.
would be next week.

Regards.

**Comment by akshay2000** [comment]
In that case, I guess I'll have to wait until then and manually set the args once the session loads.

**Comment by phoityne** [comment]
this feature has been added in release-0.0.15.0.
