### ISSUE TITLE
How can I add it to the environment path. I'm a archlinux user.

### ISSUE THREAD

**Issue by aurexav** [phoityne/phoityne-vscode#7]
I don't know how to configure launch.json.

After I ran stack install phoityne-vscode, what should I do?

Can you give me some tips?

**Comment by phoityne** [comment]
I am not sure on archlinux, but probably phoityne is installed in ~/.local/bin.
Firstly, check it like below.

`$ ls ~/.local/bin/phoityne-vscode`
`/home/{your username}/.local/bin/phoityne-vscode`
`$`

It shows full path to the phoityne-vscode.
Then set this path(to bin directory) to PATH environment.

[on bash]
`$ export PATH=$PATH:/home/{your username}/.local/bin`

[on csh]
`$ setenv PATH ${PATH}:/home/{your username}/.local/bin`

Just to be sure that phoityne is on your path,
check as below.

`$ phoityne-vscode --version`
`phoityne-vscode-0.0.11.0`
`$`

Finally run code.

`$ code`

vscode will be started.

Regards.

**Comment by acgxv** [comment]
![1](https://cloud.githubusercontent.com/assets/16152305/21317417/f62559ce-c63f-11e6-839d-5cde1cad2029.png)

Thanks your reply,
but still this problem...  : (

**Comment by phoityne** [comment]
Could you run code from terminal like below ?
(because in above picture, I can not see 'code' on ternimal last line.)

```
$ which phoityne-vscode
/home/{your username}/.local/bin/phoityne-vscode

$ code
(vscode will be started)
```

Regards.

**Comment by acgxv** [comment]
Oh it works. 👍
