### ISSUE TITLE
Unterminated process after leaving GHCi

### ISSUE THREAD

**Issue by seungha-kim** [phoityne/phoityne-vscode#8]
First of all, thank you for your great work!
I tried to run this extension on Ubuntu 16.04, but it seems phoityne-vscode processe falls into infinite loop everytime it leaves GHCi.
Screenshot here:
![image](https://cloud.githubusercontent.com/assets/767106/21331864/2d5bd326-c688-11e6-8885-8fc94bdc2562.png)

**Comment by acgxv** [comment]
I had not noticed this before.

When I see your issues, I found that I have the same problem...

**Comment by phoityne** [comment]
Thank you for the report.
Fixing it in the next release.

Regards.

**Comment by phoityne** [comment]
Fixed in phoityne-vscode-0.0.12.0.
