### ISSUE TITLE
Source Code for plugin

### ISSUE THREAD

**Issue by sumo** [phoityne/phoityne-vscode#9]
Have you or can you release the source for the plugin and the repository for the haskell backend? This will probably make an ideal starting point for adding Intero support to VSCode. I would like to help with that if possible.

**Comment by phoityne** [comment]
Hi.

> Have you or can you release the source for the plugin and the repository for the haskell backend? 

No, I haven't.
now preparing to move from local svn repository to github.

Currently, you can get this extension by installation on vscode.
On Windows, you will find downloaded  extension  in this folder.
`
    C:\Users\{account}\.vscode\extensions
`
It includes setting file(package.json) and a bat files.

And haskell things are [here](https://hackage.haskell.org/package/phoityne-vscode).
thanks.

**Comment by akshay2000** [comment]
> Currently, you can get this extension by installation on vscode.
On Windows, you will find downloaded extension in this folder.
C:\Users\{account}\.vscode\extensions
It includes setting file(package.json) and a bat files.

Will this allow me to temporarily edit the extension so that I can set args as mentioned in #5?

**Comment by phoityne** [comment]
No, that won't. not enough.

you also have to get phoityne-vscode code from [hackage](https://hackage.haskell.org/package/phoityne-vscode), modify it to run ":set args" on ghci at debug session start, then build and install it.

At this moment, I don't  have time to investigate this implementation possibility.

**Comment by phoityne** [comment]
commited source code.
